- name: Install and restart nginx
  hosts: all
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest
      register: install_nginx

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
      when: install_nginx.changed or install_nginx.failed == false
